### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by C0desmasher** [C0desmasher/Quiz-Application#1]
There is some error when you go to last page(Score page), At there calculation is not performing in well manner and the score is not printing. please solve if you can

**Comment by xPretender** [comment]
Hello! I solved the score calculations. I will fork and send a pull request today.

**Comment by C0desmasher** [comment]
why you didn't removed the calculating score code from action_performed method. quick do it bro.

**Comment by C0desmasher** [comment]
Thank you guys.
