### ISSUE TITLE
Last option not showing in Q3

### ISSUE THREAD

**Issue by arimallick** [C0desmasher/Quiz-Application#2]
In question 3: ``Inheritence is used for``
the last option "all of the above" (which is also the answer!) is not shown!!

1. Fix option-not-shown issue.
2. Change the spelling of ``Inheritence`` to ``Inheritance``.

**Comment by arimallick** [comment]
@C0desmasher 
If you assign this to me, I can fix both these issues.

**Comment by C0desmasher** [comment]
spelling mistake is not an issue because that is stored as string.
ex -   String question = "Inheritence"; // it will not throw error. whether the spelling is mistaken or not.

**Comment by C0desmasher** [comment]
I want to fix the QuizScore.java file.
After completing the game the score is not showing it shows 0 all time -> this is an issue
